# Generated by Django 3.0.5 on 2020-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejcomplaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complain_about', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('complain_too', models.CharField(max_length=50)),
                ('complain', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='faculity_info',
            name='email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculity_info',
            name='user_name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
