# Generated by Django 3.0.5 on 2020-06-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0002_auto_20200620_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomplaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complain_about', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('complain_too', models.CharField(max_length=50)),
                ('complain', models.TextField()),
                ('user', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
