# Generated by Django 3.0.5 on 2020-06-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0005_auto_20200623_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomplaint',
            name='send_to',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
