# Generated by Django 3.0.5 on 2020-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0007_remove_rejcomplaint_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='solcomplaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complain_about', models.CharField(max_length=50)),
                ('solution', models.TextField()),
                ('complain_too', models.CharField(max_length=50)),
                ('complain', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
