# Generated by Django 3.0.5 on 2020-07-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0009_acomplaint_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acomplaint',
            name='email',
        ),
    ]
