# Generated by Django 3.0.5 on 2020-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0011_auto_20200710_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='acomplaint',
            name='email',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
