# Generated by Django 3.0.5 on 2020-07-11 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faculity', '0012_acomplaint_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appcomplaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('complain_about', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=254)),
                ('complain_too', models.CharField(max_length=50)),
                ('complain', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
