# Generated by Django 3.0.5 on 2020-07-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculity', '0013_appcomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('complain_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
